# -*- coding: utf-8 -*-
"""UTS-2702275794-no3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CVVloTkq_ncFBS7_s0BmDa9_vBEnn1lb
"""

import pickle
import numpy as np

# Load model
with open('best_model.pkl', 'rb') as f:
    model = pickle.load(f)

def predict_from_input(input_array):
    """
    Menerima input sebagai array

    """
    input_np = np.array(input_array).reshape(1, -1)
    prediction = model.predict(input_np)
    return prediction[0]

# Panggil fungsi di sini
test_input = [45, 7, 1, 2, 0, 1, 0, 3, 0.75, 0, 6, 11, 13, 20, 35, 28, 17, 25]
print("Prediksi:", predict_from_input(test_input))